CREATE TABLE PERSON (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY,
	first_name varchar(255) not null,
	last_name varchar(255) not null
);

insert into PERSON (first_name, last_name) values ('Dave', 'Syer');
insert into PERSON (first_name, last_name) values ('John', 'Connor');
insert into PERSON (first_name, last_name) values ('Sarah', 'Connor');
insert into PERSON (first_name, last_name) values ('Kyle', 'Reese');
insert into PERSON (first_name, last_name) values ('Nick', 'Stahl');
insert into PERSON (first_name, last_name) values ('Edward', 'Furlong');
insert into PERSON (first_name, last_name) values ('Christian', 'Bale');