CREATE TABLE CITY (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    name varchar(255) not null,
    state varchar(2) not null
);

CREATE TABLE EQUIPMENT_MODEL (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    name varchar(255) not null,
    model_code varchar(50) not null
);

CREATE UNIQUE INDEX EQUIPMENT_MODEL_IDX01_NAME ON EQUIPMENT_MODEL (name);
CREATE UNIQUE INDEX EQUIPMENT_MODEL_IDX02_MODEL ON EQUIPMENT_MODEL (model_code);

CREATE UNIQUE INDEX CITY_IDX01_STATE ON CITY (state, name);

insert into CITY(name, state) values ('Porto Alegre', 'RS');
insert into CITY(name, state) values ('Rio de Janeiro', 'RJ');
insert into CITY(name, state) values ('Canoas', 'RS');
insert into CITY(name, state) values ('Petropolis', 'RJ');


insert into EQUIPMENT_MODEL(name, model_code) values ('Model R2D2', 'R2D2');
insert into EQUIPMENT_MODEL(name, model_code) values ('Model C3PO', 'C3PO');
insert into EQUIPMENT_MODEL(name, model_code) values ('Model T-800', 'T-800');
insert into EQUIPMENT_MODEL(name, model_code) values ('Model T-1000', 'T-1000');